### ISSUE TITLE
Link in Forky's resource returns a 404 error and kills the game

### ISSUE THREAD

**Issue by FeliciaSullivan** [engagementgamelab/CivicSeed#225]
The document attached to Forky (level 3) -- throws a 404 error and then goes to the document.  The document opens in the game window and am uable to return to the game.  i need to refresh the whole game before returning to game.

**Comment by louh** [comment]
This is a weird one but I figured out what's going on. It's a link on the same domain, so Davis (front-end routing library) is attempting to capture it, which results in the 404. I've rewritten the code so that the link is now using an event handler to interrupt Davis and do what I want it to do (load in another window).

Fixed in commit e78c6e08aed0c5ce584f1c88303e363e06c39d74
